version: '3.3'
services:
  mongo_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      backend:
        aliases:
          - post_db
          - comment_db
  ui:
    image: ${USERNAME}/ui:${UI_VERSION}
    ports:
      - ${UI_PORT}:${UI_PORT}/tcp
    networks:
      - frontend
  post:
    image: ${USERNAME}/post:${POST_VERSION}
    networks:
      - backend
      - frontend
  comment:
    image: ${USERNAME}/comment:${COMMENT_VERSION}
    networks:
      - backend
      - frontend
  prometheus:
    image: ${USERNAME}/prometheus
    ports:
      - '9090:9090'
    networks:
      - frontend
  cadvisor:
    image: google/cadvisor:latest
    volumes:
      - '/:/rootfs:ro'
      - '/var/run:/var/run:rw'
      - '/sys:/sys:ro'
      - '/var/lib/docker/:/var/lib/docker:ro'
    depends_on:
      - prometheus
    ports:
      - '8080:8080'
    networks:
      - frontend
  node-exporter:
    image: prom/node-exporter:v0.17.0
    user: root
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
    depends_on:
      - prometheus
    networks:
      - frontend
  mongodb-exporter:
    image: eses/mongodb_exporter:latest
    environment:
    - MONGODB_URI=mongodb://mongo_db:27017
    depends_on:
      - prometheus
    networks:
      - frontend
      - backend
  blackbox:
    image: prom/blackbox-exporter:latest
    depends_on:
      - prometheus
    ports:
      - '9115:9115'
    networks:
      - frontend
  grafana:
    image: grafana/grafana
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=secret
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    networks:
      - frontend
  alertmanager:
    image: ${USERNAME}/alertmanager
    command:
      - '--config.file=/etc/alertmanager/config.yml'
    ports:
      - 9093:9093
    networks:
      - frontend

volumes:
  post_db:
  grafana_data:

networks:
  frontend:
    ipam:
      driver: default
      config:
        - subnet: ${FRONTEND_SUBNET}
  backend:
    ipam:
      driver: default
      config:
        - subnet: ${BACKEND_SUBNET}
