version: '3.3'
services:
  mongo_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      backend:
        aliases:
          - post_db
          - comment_db
  ui:
    build: ./ui
    image: ${USERNAME}/ui:${UI_VERSION}
    ports:
      - ${UI_PORT}:${UI_PORT}/tcp
    networks:
      - frontend
  post:
    build: ./post-py
    image: ${USERNAME}/post:${POST_VERSION}
    networks:
      - backend
      - frontend
  comment:
    build: ./comment
    image: ${USERNAME}/comment:${COMMENT_VERSION}
    networks:
      - backend
      - frontend
volumes:
  post_db:

networks:
  frontend:
    ipam:
      driver: bridge
      config:
        - subnet: ${FRONTEND_SUBNET}
  backend:
    ipam:
      driver: bridge
      config:
        - subnet: ${BACKEND_SUBNET}
