# Playbook for Reddit application code deploy
---
- name: Deploy application
#  hosts: tag_reddit-app
  hosts: app
  become: yes
  vars:
    app: reddit
    deploy_user: appuser
    app_dir: /home/{{ deploy_user }}/{{ app }}

  tasks:
  - name: Checkout Reddit App git repo
    git:
      repo: "https://github.com/silazare/{{ app }}.git"
      dest: "{{ app_dir }}"
      version: "{{ git_commit_hash | default('HEAD') }}"
      force: yes
      update: yes
    notify: restart puma

  - name: Install Reddit App
    bundler:
      state: present
      chdir: "{{ app_dir }}"
    notify: restart puma

  handlers:
  - name: restart puma
    become: yes
    service:
      name: puma
      state: restarted
