# Playbook for Packer DB AMI build
# Direct execution: ansible-playbook -u ubuntu -i 35.195.76.112, reddit_app.yml --private-key=~/.ssh/ubuntu
---
- name: Reddit App -- Install MongoDB
  hosts: all
  gather_facts: yes
  become: yes

  tasks:
  - name: Add mongodb-org repo key
    apt_key:
      keyserver: hkp://keyserver.ubuntu.com
      id: 2930ADAE8CAF5059EE73BB4B58712A2291FA4AD5
      state: present

  - name: Add mongodb-org repo
    apt_repository:
      repo: "deb http://repo.mongodb.org/apt/ubuntu {{ ansible_distribution_release }}/mongodb-org/3.6 multiverse"
      update_cache: yes

  - name: Install mongodb-org
    apt:
      pkg: mongodb-org
      state: present
      update_cache: yes

  - name: Enable mongod service
    service:
      name: mongod
      enabled: yes
      state: started
