# Playbook for Reddit App Configuration Management
# Execution with Static Inventory:
#  ansible-playbook reddit_app.yml

# Execution with Static Inventory and separate hosts or tags:
#  ansible-playbook reddit_app.yml --limit db
#  ansible-playbook reddit_app.yml --limit app --tags app-tag
#  ansible-playbook reddit_app.yml --limit app --tags deploy-tag

# Execution with Dynamic Inventory:
#  ansible-playbook reddit_app.yml -i gce.py

---
- name: Configure MongoDB host
  hosts: tag_reddit-db
#  hosts: db
  become: yes
  tags: db-tag
  vars:
    mongo_bind_ip: 0.0.0.0

  tasks:
  - name: Register MongoDB internal IP
    debug:
      msg: "{{ gce_private_ip }}"
    register: db_internal_ip
    when: gce_private_ip is defined

  - name: Change mongo config file
    template:
      src: templates/mongod.conf.j2
      dest: /etc/mongod.conf
      mode: 0644
    notify: restart mongod

  handlers:
  - name: restart mongod
    service:
      name: mongod
      state: restarted

- name: Configure App host
  hosts: tag_reddit-app
#  hosts: app
  become: yes
  tags: app-tag
  vars:
    db_host: 10.132.0.2
    app: reddit
    app_dir: /home/appuser/{{ app }}

  tasks:
  - name: Set MongoDB internal IP as db_host
    set_fact:
      db_host: "{{ hostvars['reddit-db']['db_internal_ip'].msg }}"
    when: hostvars['reddit-db'] and hostvars['reddit-db']['db_internal_ip'] is defined

  - name: Add unit file for Puma
    template:
      src: templates/puma.service.j2
      dest: /etc/systemd/system/puma.service
      mode: 0644
    notify: reload puma

  - name: Add config for DB connection
    template:
      src: templates/db_config.j2
      dest: /home/appuser/db_config
      owner: appuser
      group: appuser
    notify: reload puma

  - name: Enable puma
    systemd:
      name: puma
      enabled: yes

  handlers:
  - name: reload puma
    service:
      name: puma
      state: reloaded

- name: Deploy application
  hosts: tag_reddit-app
#  hosts: app
  tags: deploy-tag
  vars:
    app: reddit
    app_dir: /home/appuser/{{ app }}

  tasks:
  - name: Checkout Reddit App git repo
    git:
      repo: "https://github.com/silazare/{{ app }}.git"
      dest: "{{ app_dir }}"
      version: "{{ git_commit_hash | default('HEAD') }}"
      force: yes
      update: yes
    notify: restart puma

  - name: Install Reddit App
    bundler:
      state: present
      chdir: "{{ app_dir }}"
    notify: restart puma

  handlers:
  - name: restart puma
    become: yes
    service:
      name: puma
      state: restarted
