# ansible-playbook -u appuser -i hosts reddit_app_deploy.yml --private-key=~/.ssh/appuser
---
- name: Reddit App -- Deploy application
  hosts: reddit_app
  gather_facts: no
  vars:
    app: reddit
    app_dir: /home/appuser/{{ app }}

  tasks:
  - name: Checkout Reddit App git repo
    git:
      repo: "https://github.com/silazare/{{ app }}.git"
      dest: "{{ app_dir }}"
      version: "{{ git_commit_hash | default('HEAD') }}"
      force: yes
      update: yes
    notify: restart puma

  - name: Install Reddit App
    bundler:
      state: present
      chdir: "{{ app_dir }}"
    notify: restart puma

  - name: Deploy puma systemd file
    become: yes
    template:
      src: templates/puma.service
      dest: /etc/systemd/system/puma.service
      owner: root
      group: root
      mode: "0644"
    notify: restart puma

  - name: Enable puma service
    become: yes
    service:
      name: puma
      enabled: yes
      state: started

  handlers:
  - name: restart puma
    become: yes
    service:
      name: puma
      state: restarted
